name: Check Branch Naming

on:
  push:
    branches:
      - '**'              # include all branches
      - '!master'         # exclude master
      - '!feature/**'     # exclude feature/*
      - '!bugfix/**'      # exclude bugfix/*
      - '!release/**'     # exclude release/*
  pull_request:
    branches:
      - '**'
      - '!master'
      - '!feature/**'
      - '!bugfix/**'
      - '!release/**'

jobs:
  fail-on-unexpected-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the workflow due to unexpected branch name
        run: |
          echo "❌ Branch '${GITHUB_REF#refs/heads/}' is not allowed."
          echo "✅ Only 'feature/', 'bugfix/' and 'release/'  are allowed."
          exit 1
