name: Cleanup Orphan Preview Artifacts

on:
  schedule:
    - cron: '0 3 * * 0'   # Todos os domingos às 03:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old preview artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3 days'                # Artefatos com mais de 3 dias
          name: '^preview-.*'         # Regex que garante correspondência com qualquer nome que comece com 'preview-'
          token: ${{ secrets.GITHUB_TOKEN }}
