name: Manual Custom Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão customizada (ex: 1.2.3)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update manifest.json version
        run: |
          jq --arg version "${{ github.event.inputs.version }}" '.version = $version' manifest.json > tmp.json && mv tmp.json manifest.json

      - name: Read .compact-ignore and zip files
        run: |
          if [ ! -f .compact-ignore ]; then
            echo ".compact-ignore not found, creating an empty one."
            touch .compact-ignore
          fi
          zip -r release.zip . -x@.compact-ignore

      - name: Commit updated manifest.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add manifest.json
          git commit -m "chore: update version to ${{ github.event.inputs.version }}"
          git push

      - name: Create Tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
