name: Manual Custom Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão customizada (ex: 1.2.3)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # Impede conflitos com o uso do PAT manual

      - name: Set Git remote with PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}

      - name: Update manifest.json version
        run: |
          jq --arg version "${{ github.event.inputs.version }}" '.version = $version' manifest.json > tmp.json && mv tmp.json manifest.json

      - name: Read .compact-ignore and zip files with versioned name
        run: |
          if [ ! -f .compact-ignore ]; then
            echo ".compact-ignore not found, criando um vazio."
            touch .compact-ignore
          fi
          zip -r ${{ github.event.inputs.version }}.zip . -x@.compact-ignore

      - name: Commit updated manifest.json (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add manifest.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update version to ${{ github.event.inputs.version }}"
            git push origin HEAD:master
          else
            echo "No changes to commit."
          fi

      - name: Create Tag
        run: |
          TAG=${{ github.event.inputs.version }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping tag creation."
          else
            git tag "$TAG"
            git push origin refs/tags/"$TAG"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: ${{ github.event.inputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
