name: Manual Custom Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão customizada (ex: 1.2.3)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set Git remote with PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |-
          set -euo pipefail
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}

      - name: Update manifest.json version
        run: |-
          set -euo pipefail
          jq --arg version "${{ github.event.inputs.version }}" '.version = $version' manifest.json > tmp.json && mv tmp.json manifest.json

      - name: Prepare upload folder excluding files from .compact-ignore
        run: |-
          set -euo pipefail
          if [ ! -f .compact-ignore ]; then
            echo ".compact-ignore not found, creating an empty one."
            touch .compact-ignore
          fi
          rm -rf upload-folder
          mkdir upload-folder
          rsync -av --exclude-from='.compact-ignore' ./ upload-folder/ --exclude=upload-folder

      - name: Commit updated manifest.json (if changed)
        run: |-
          set -euo pipefail
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add manifest.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update version to ${{ github.event.inputs.version }}"
            git push origin HEAD:master
          else
            echo "No changes to commit."

      - name: Create Git tag
        run: |-
          set -euo pipefail
          TAG=${{ github.event.inputs.version }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping tag creation."
          else
            git tag "$TAG"
            git push origin refs/tags/"$TAG"
          fi

      - name: Create ZIP archive with version name
        run: |-
          set -euo pipefail
          cd upload-folder
          zip -r ../${{ github.event.inputs.version }}.zip ./*
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: ${{ github.event.inputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
